-- Switch identity columns from ALWAYS to BY DEFAULT so the SQLite -> Supabase
-- data migration can preserve original ids. Apply once to any project that
-- already ran 001_init.sql before this change landed.

alter table players  alter column id set generated by default;
alter table matches  alter column id set generated by default;
