-- PingPongZS Schema Extension: 2v2 Doubles Support & Multi-Season System

-- 1. Extend matches table for 2v2 doubles and seasons
alter table matches add column if not exists player_a2_id bigint references players(id) on delete restrict;
alter table matches add column if not exists player_b2_id bigint references players(id) on delete restrict;
alter table matches add column if not exists match_type text not null default '1v1';
alter table matches add column if not exists season integer not null default 1;

create index if not exists matches_player_a2_idx on matches(player_a2_id);
create index if not exists matches_player_b2_idx on matches(player_b2_id);
create index if not exists matches_season_idx    on matches(season);
create index if not exists matches_type_idx      on matches(match_type);

-- 2. Seasons table to track active and archived seasons
create table if not exists seasons (
  id           integer primary key,
  name         text not null,
  status       text not null default 'active' check (status in ('active', 'archived')),
  baseline_mmr integer not null default 1200,
  created_at   timestamptz not null default now()
);

-- Seed Season 1 (archived) and Season 2 (active)
insert into seasons (id, name, status, baseline_mmr)
values
  (1, 'Season 1', 'archived', 1000),
  (2, 'Season 2', 'active', 1200)
on conflict (id) do update set
  name = excluded.name,
  status = excluded.status,
  baseline_mmr = excluded.baseline_mmr;

-- 3. Player seasonal statistics tracking table
create table if not exists player_seasons (
  id                  bigint generated by default as identity primary key,
  player_id           bigint      not null references players(id) on delete cascade,
  season              integer     not null references seasons(id) on delete cascade,
  mmr                 integer     not null default 1200,
  wins                integer     not null default 0,
  losses              integer     not null default 0,
  points_scored       integer     not null default 0,
  points_conceded     integer     not null default 0,
  current_win_streak  integer     not null default 0,
  current_loss_streak integer     not null default 0,
  created_at          timestamptz not null default now(),
  unique(player_id, season)
);

create index if not exists player_seasons_player_season_idx on player_seasons(player_id, season);
create index if not exists player_seasons_season_mmr_idx    on player_seasons(season, mmr desc);

-- Realtime publications
alter publication supabase_realtime add table seasons;
alter publication supabase_realtime add table player_seasons;
